### ISSUE TITLE
Unity crashes when exiting Play Mode after BasicKyle is Converted To Player (tutorial)

### ISSUE THREAD

**Issue by tah0ma** [emotitron/Simple_Addon_for_Pun2#4]
Hello, I am working through the "Simple Getting Started Tutorial" ([https://doc.photonengine.com/en-us/pun/current/simple/simple-tutorial](https://doc.photonengine.com/en-us/pun/current/simple/simple-tutorial)) however Unity crashes when exiting Play Mode once BasicKyle is Converted To Player and the relevant components are added.

Unity 2020.3.21f1
PUN 2.39

**Comment by emotitron** [comment]
We have been winding down support for Simple for quite a while now (since
Fusion was started and is the intended replacement for anything Simple
would be used for). I would recommend getting in on the Fusion beta rather
than doing anything with Simple/PUN at this point if you are just getting
started.

**Comment by tah0ma** [comment]
Thanks for the reply, I hadn't realized PUN was moved to legacy. I'll check out Fusion when I have a chance!
